### ISSUE TITLE
Option to always send full DMX array

### ISSUE THREAD

**Issue by martinzuern** [hobbyquaker/artnet#10]
It would be helpful, if art net could be configured to always send the full DMX data instead of the only changed ones. 
I've a setup with a raspberry pi and Ola running, and it only really works when the full data is always send.
Would you accept a PR?

**Comment by hobbyquaker** [comment]
Sure, if you do it default off I have no concerns with this. Would be nice if you update the Readme and document the new option :-)

**Comment by hobbyquaker** [comment]
thx 👍

**Comment by hobbyquaker** [comment]
published 1.1.0 on npm
