### ISSUE TITLE
More than one host?

### ISSUE THREAD

**Issue by TheFonix** [hobbyquaker/artnet#12]
Is there any way of sending the artnet data to multiple hosts? Ive tried:
```
var options = {
    host: '10.0.0.18' 
};
var options = {
    host: '10.0.0.30' 
};
```
and 
```
var options = {
    host: '10.0.0.18,10.0.0.30'
};
```
But neither seem to work, any help would be great, thanks

**Comment by hobbyquaker** [comment]
Until now there is no possibility to send to two distinct hosts. As a workaround: You could either use the Broadcast Adress 255.255.255.255 (if your Network and your Artnet Nodes support this) or create multiple Artnet instances and loop over them like e.g.:
```javascript
var artnets = [
  require('artnet')({
    host: '10.0.0.18'
  }),
  require('artnet')({
    host: '10.0.0.30'
  })
];

function setAll(channel, value) {
  artnets.forEach(artnet => {
    artnet.set(channel, value);
  });
}

setAll(1, 255);
```
(untested)

**Comment by Foxhunt** [comment]
Can confirm
> or create multiple Artnet instances and loop over them

works well.

See [here](https://github.com/Foxhunt/NVIS/blob/master/nvis_node_snmp/ArtNet.js#L10) and [here](https://github.com/Foxhunt/NVIS/blob/master/nvis_node_snmp/ArtNet.js#L61).
