### ISSUE TITLE
[Feature] Send ArtTrigger packets

### ISSUE THREAD

**Issue by jnovack** [hobbyquaker/artnet#19]
I have an application which can process ArtTrigger packets.

As an example, the popular DMXKing devices can process ArtTrigger packets to play/stop/record shows. https://dmxking.com/downloads/eDMX%20PRO%20Recorder%20Manual%20(EN).pdf

Would this be in-scope of this package and be feasible?

Thank you for your consideration.

ArtTrigger References:
* http://art-net.org.uk/wordpress/?page_id=968
* https://www.artisticlicence.com/WebSiteMaster/User%20Guides/art-net.pdf

**Comment by hobbyquaker** [comment]
As long as we try our best to keep the api compatible I have no concerns about adding other ArtNet packet types. But I can't tell you when I find time and motivation to do this - it's especially hard for me to find motivation when I don't feel a need and don't plan to use that feature... 

But: Pull Requests welcome! ;-)
