### ISSUE TITLE
Can't seem to initialize more than 1 instance

### ISSUE THREAD

**Issue by natcl** [hobbyquaker/artnet#3]
Hello,

I need to send on more than 1 universe from within the same code.  I'm trying to create multiple instances of the artnet library but it does not seem to work.  Is it possible to do this ?
Thanks

**Comment by hobbyquaker** [comment]
Hi,

I published a new version of the module, now you can send to multiple universes:

``` javascript
artnet.send(0, 1, 255); // set channel 1 in universe 0 to 255
artnet.send(2, 1, 255); // set channel 1 in universe 2 to 255
```

I own a Artnet node that only supports one universe, so i can't test that - would be glad to hear from you if it works as expected.

Pls mind the changes in the interface, see Readme.

Regards,
Sebastian

**Comment by hobbyquaker** [comment]
...forgot to mention: you can now use multiple instances of the module too.
