### ISSUE TITLE
lib does not work

### ISSUE THREAD

**Issue by coral** [hobbyquaker/artnet#4]
trying to send 8 universes full of data, rate limiting breaks apart.

**Comment by hobbyquaker** [comment]
hi, I just published a little update fixing a bug and I also added a test-script:
https://github.com/hobbyquaker/artnet/blob/master/test.js

this script sets data on all channels in 8 universes at a refresh rate of 25Hz - and this seems to work. 
Could you describe the issue more closely or demonstrate it with a test-script?

**Comment by hobbyquaker** [comment]
please re-open if the issue persists
