### ISSUE TITLE
Universe length may be wrong

### ISSUE THREAD

**Issue by koopero** [hobbyquaker/artnet#5]
I was unable to get this module working for a project I'm putting together. Specifically, I am using a single DMX King eDMX1. It seems that the length field of the outgoing Art-Net packet may be wrong. The line `var lLen = (length & 0xfe) + 2;` is making it send a universe length of 514. 

If I have time later, I'll put together a patch and test it out.

**Comment by hobbyquaker** [comment]
Oh yes, you're right. Don't know what I was thinking when I wrote this Code ;-) Just released version 1.0.2, that should fix this issue. Could you test it please?

https://github.com/hobbyquaker/artnet/commit/a0331658e81cd25270d51d8fdff2f6d861fb21b6

**Comment by koopero** [comment]
I'll give it a try tonight, but I think you should take another look.  On
the off chance `length == 255`, this would fail. You would be better
changing `length` rather than `lLen`.

**Comment by hobbyquaker** [comment]
Oh, yes. Thanks for the hint! 
v1.0.3: https://github.com/hobbyquaker/artnet/commit/669cd1ce13a605f92c5b23cd12ff2b8bd5395d16

**Comment by koopero** [comment]
Can confirm this works with the eDMX1! Great job and thanks for this module. :)
